[package]
name = "tui-big-text"
version = "0.1.0"
edition = "2021"
description = "A simple Ratatui widget for displaying big text using the font8x8 crate in a TUI (Terminal UI)."
license = "MIT OR Apache-2.0"
repository = "https://github.com/joshka/tui-big-text"
authors = ["Joshka"]
categories = ["command-line-interface", "gui"]
keywords = ["cli", "console", "ratatui", "terminal", "tui"]

[dependencies]
derive_builder = "0.12.0"
font8x8 = "0.3.1"
itertools = "0.11.0"
ratatui = "0.23.0"

[dev-dependencies]
anyhow = "1.0.44"
indoc = "2.0.3"
crossterm = "0.27.0"
